FROM bitwalker/alpine-elixir-phoenix:1.9.4
RUN mix local.hex --force && mix local.rebar --force
RUN apk --update add postgresql-client

COPY . /app/

WORKDIR /app

RUN mix do deps.get, deps.compile
RUN npm install --prefix assets

EXPOSE 4000
CMD ["./bin/run.sh"]
